# Generated by Django 5.1.4 on 2024-12-15 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_currency_icon_alter_currency_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['id'], 'verbose_name': '货币', 'verbose_name_plural': '货币'},
        ),
    ]
