# Generated by Django 5.1.4 on 2024-12-17 20:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_currency_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['created_date'], 'verbose_name': '账户', 'verbose_name_plural': '账户'},
        ),
        migrations.AlterField(
            model_name='account',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.currency', verbose_name='货币'),
        ),
        migrations.AlterField(
            model_name='account',
            name='icon',
            field=models.CharField(choices=[('fas fa-wallet', 'Wallet'), ('fas fa-piggy-bank', 'Piggy Bank'), ('fas fa-coins', 'Coins')], default='fas fa-wallet', max_length=100, verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=100, verbose_name='账户名称'),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日期'),
        ),
    ]
