# Generated by Django 5.1.4 on 2024-12-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_account_options_alter_account_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='icon',
            field=models.CharField(choices=[('fa fa-wallet', 'Wallet'), ('fa fa-piggy-bank', 'Piggy Bank'), ('fa fa-coins', 'Coins')], default='fas fa-wallet', max_length=100, verbose_name='图标'),
        ),
    ]
