# Generated by Django 5.1.4 on 2024-12-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_account_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='icon',
            field=models.CharField(default='fa fa-money', max_length=100, verbose_name='图标'),
        ),
    ]
