# Generated by Django 5.1.4 on 2024-12-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_account_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('income', '收入'), ('expense', '支出')], default='收入', max_length=100),
        ),
    ]
