# Generated by Django 5.1.4 on 2024-12-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_alter_account_options_alter_currency_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='icon',
            field=models.CharField(max_length=100, verbose_name='Font 图标'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
    ]
