# Generated by Django 2.1.7 on 2021-04-08 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='班级名称')),
                ('num', models.CharField(max_length=20, verbose_name='年级')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('age', models.SmallIntegerField(null=True, verbose_name='年龄')),
                ('sex', models.SmallIntegerField(default=1, verbose_name='性别')),
                ('qq', models.CharField(max_length=20, unique=True, verbose_name='QQ')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='电话')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.Grade')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=20, verbose_name='学院')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
        ),
    ]
