# Generated by Django 3.2.5 on 2021-11-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20210409_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='qq',
            field=models.CharField(error_messages={'unique': 'qq号码重复！'}, max_length=20, unique=True, verbose_name='QQ'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.SmallIntegerField(choices=[[0, '女'], [1, '男']], default=1, verbose_name='性别'),
        ),
    ]
