# Generated by Django 3.2.5 on 2022-03-17 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logsheet',
            name='correction',
        ),
        migrations.RemoveField(
            model_name='logsheet',
            name='self_comment',
        ),
        migrations.RemoveField(
            model_name='logsheet',
            name='self_index',
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction', models.IntegerField(default=0)),
                ('self_index', models.IntegerField(default=100)),
                ('self_comment', models.TextField()),
                ('log_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weatherapp.logsheet')),
            ],
            options={
                'verbose_name': 'Condition',
                'verbose_name_plural': 'Condition',
            },
        ),
    ]
