# Generated by Django 3.2.5 on 2022-03-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0002_auto_20220317_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_data', models.CharField(max_length=200)),
                ('all_index', models.IntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Recommend',
                'verbose_name_plural': 'Recommend',
            },
        ),
    ]
