# Generated by Django 3.2.5 on 2022-03-17 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0003_recommend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='log_sheet',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='self_comment',
        ),
    ]
